server:
    port: ${SERVER_PORT}

spring:
    application:
        name: workflow-service
    datasource:
        url: ${DB_URL_CONNECTION}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop