apiVersion: v1
kind: Service
metadata:
    name: autotasks-workflow_service
    namespace: autotasks_development
    labels:
        app: workflow_service
        env: development
        tier: backend
spec:
    selector:
        app: workflow_service
    type: ClusterIP
    ports:
        - protocol: TCP
          port: 8082
          targetPort: 8082
